### ISSUE TITLE
Add Arrow to Read More

### ISSUE THREAD

**Issue by ilincaroman** [raduconst/begonia#12]
"Read more" nu are sageata din design:

![](https://puu.sh/uY8NS/324aee26f8.png)

Design:

![read more button](https://cloud.githubusercontent.com/assets/15910943/24325267/b2831d88-119d-11e7-93fb-b8ac2efc2dc5.png)

@Robertght ai nevoie de vreun exportable, sau poti face din CSS treaba asta? Suppose this would help: http://stackoverflow.com/questions/27492191/how-to-make-a-fancy-arrow-using-css

**Comment by Robertght** [comment]
Acum are si am facut-o din CSS: http://dev.code711.com/demos/begonia/
